@echo off
setlocal enabledelayedexpansion

echo ============================================================
echo  PTAI - First Time Setup - 48GB RAM ULTIMATE - BEST CONFIG
echo  Local Autonomous Trading Agent - Polymarket + LM Studio
echo  Optimized for 48GB RAM - 70B Models + R1/X FIX
echo ============================================================
echo.

echo [1/10] Checking Python...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Python not found! Install Python 3.10+ from https://python.org
    echo Check "Add Python to PATH" during install
    pause
    exit /b 1
)
python --version
echo Python found - OK
echo.

echo [2/10] Creating virtual environment...
if not exist .venv (
    echo Creating .venv...
    python -m venv .venv
    if %errorlevel% neq 0 (
        echo ERROR: Failed to create venv
        pause
        exit /b 1
    )
) else (
    echo .venv already exists - OK
)
echo.

echo [3/10] Activating venv and upgrading pip...
call .venv\Scripts\activate.bat
python -m pip install --upgrade pip --quiet
echo Pip upgraded - OK
echo.

echo [4/10] Installing PTAI dependencies (2-3 minutes)...
pip install -r requirements.txt --quiet
if %errorlevel% neq 0 (
    echo WARNING: Some packages failed, retrying...
    pip install -r requirements.txt
)
echo Dependencies installed - OK
echo.

echo [5/10] Installing Playwright browser (Chromium)...
playwright install chromium
if %errorlevel% neq 0 (
    python -m playwright install chromium
)
echo Playwright installed - OK
echo.

echo [6/10] Creating folders...
if not exist data mkdir data
if not exist logs mkdir logs
if not exist browser\profiles\default mkdir browser\profiles\default
if not exist config mkdir config
echo Folders created - OK
echo.

echo [7/10] Setting up config files...
if not exist .env (
    copy .env.example .env >nul
    echo .env created
) else (
    echo .env already exists - OK
)
if not exist config\config.yaml (
    copy config\config.yaml.example config\config.yaml >nul
    echo config.yaml created
) else (
    echo config.yaml already exists - OK
)
echo.

echo [8/10] Applying BEST CONFIG for 48GB RAM - 70B MODELS + R1/X FIX...
echo.

:: Create optimized .env for 48GB - ULTIMATE + FAST MODE
(
echo # PTAI BEST CONFIG - 48GB RAM ULTIMATE + R1/X FIX - Generated by setup.bat
echo # You have: deepseek-r1-distill-qwen-32b (SLOW 8 min), qwen/qwen3-32b (FAST 3 sec), qwen/qwen3.8-27b
echo # FAST MODE for 10-min cycle: use qwen/qwen3-32b
echo # SLOW MODE if R1: 5 deep, hourly
echo BANKROLL=50.0
echo CURRENCY=USD
echo DAILY_COST_TO_COVER=5.0
echo SHUTDOWN_IF_UNPROFITABLE_DAYS=3
echo MAX_DAILY_LOSS_PCT=0.15
echo MAX_TOTAL_DRAWDOWN_PCT=0.30
echo.
echo POLYMARKET_PRIVATE_KEY=
echo POLYMARKET_FUNDER_ADDRESS=
echo POLYMARKET_CHAIN_ID=137
echo POLYMARKET_SIGNATURE_TYPE=1
echo POLYMARKET_HOST=https://clob.polymarket.com
echo GAMMA_API=https://gamma-api.polymarket.com
echo DRY_RUN=true
echo.
echo # LLM - LM STUDIO - ULTIMATE FOR 48GB
echo # FASTEST FOR TRADING: qwen/qwen3-32b (you have it! 3 sec vs 8 min R1)
echo LLM_PROVIDER=lm_studio
echo LM_STUDIO_HOST=http://localhost:1234
echo LM_STUDIO_MODEL=local-model
echo LM_STUDIO_API_KEY=lm-studio
echo OLLAMA_HOST=http://localhost:11434
echo OLLAMA_MODEL=qwen2.5:32b
echo OPENAI_API_KEY=lm-studio
echo OPENAI_BASE_URL=http://localhost:1234/v1
echo USE_LOCAL_LLM=true
echo.
echo # X sentiment - NOW BLOCKS snscrape (404) as of 2024+ - circuit breaker auto-fails fast
echo # FIX: set false for LLM-only (fastest, avoids 13 sec delay per market, 40 sec not 21 min)
echo # RECOMMENDED: false for R1 models (R1 already slow 8 min, X makes worse)
echo SENTIMENT_USE_X=false
echo X_USE_SNSCRAPE=true
echo X_USE_BROWSER=false
echo.
echo BROWSER_HEADLESS=false
echo BROWSER_PERSISTENT_DIR=./browser/profiles/default
echo BROWSER_STEALTH=true
echo BROWSER_TIMEOUT=30000
echo.
echo # Risk - BEST - 6 percent max prevents wipeout
echo MAX_POSITION_PCT=0.06
echo MIN_EDGE_PCT=0.08
echo MAX_OPEN_POSITIONS=6
echo KELLY_FRACTION=0.5
echo MIN_LIQUIDITY=1000
echo MIN_VOLUME_24H=5000
echo.
echo # Loop - Optimized for 48GB RAM + FAST MODEL
echo # FAST: qwen3-32b 50 deep * 3 sec = 2.5 min total fits 10 min
echo # SLOW: R1 5 deep * 8 min = 40 min - use interval 60 min
echo SCAN_INTERVAL_MINUTES=10
echo SCAN_MARKETS_COUNT=500
echo MAX_DEEP_ANALYZE=50
echo SCAN_ORDER_BY=volume24hr
echo LOG_LEVEL=INFO
echo.
echo # FIXES APPLIED:
echo # - X blocking 404 circuit breaker after 3 fails 10 min
echo # - R1 slowness auto-detect: R1 32B -^> 5 deep not 30, max_tokens 500
echo # - Prompt shortened no think tag for speed
echo # - To disable X: SENTIMENT_USE_X=false (recommended for R1)
) > .env.48gb.ultimate

copy /Y .env.48gb.ultimate .env >nul
echo .env optimized for 48GB ULTIMATE + R1/X FIX - OK
echo   - Scan 500 markets
echo   - Deep analyze 50 markets (for qwen3-32b fast: 50*3sec=2.5min fits 10min)
echo   - For R1 slow: auto 5 deep (5*8min=40min - use interval 60)
echo   - SENTIMENT_USE_X=false (fastest, avoids X blocking 404 delay)
echo   - Kelly 6% max, Half-Kelly 0.5, min edge 8%
echo   - Max 6 open positions
echo.

echo [9/10] Checking LM Studio...
curl -s http://localhost:1234/v1/models >nul 2>&1
if %errorlevel% equ 0 (
    echo LM Studio running at http://localhost:1234 - GREAT!
    curl -s http://localhost:1234/v1/models
    echo.
    echo YOU HAVE (from log): deepseek-r1-distill-qwen-32b, qwen/qwen3-32b, qwen/qwen3.8-27b
    echo   R1 32B = 7-8 MIN per market SLOW due to reasoning!
    echo   qwen3-32b = 2-3 SEC per market FAST - BEST FOR TRADING!
    echo   RECOMMEND: unload R1, load qwen/qwen3-32b for 10-min cycle
    echo.
) else (
    echo LM Studio not running - will show BEST MODELS FOR 48GB:
    echo.
    echo ============================================================
    echo  BEST MODELS FOR YOUR 48GB RAM - ULTIMATE TIER:
    echo ============================================================
    echo.
    echo  #1 BEST FOR TRADING NOW - qwen/qwen3-32b (YOU HAVE IT!) FAST:
    echo     You have it loaded! 2-3 sec per market, 50 deep = 2.5 min
    echo     In LM Studio: load qwen/qwen3-32b, unload R1
    echo     .env: SENTIMENT_USE_X=false, MAX_DEEP_ANALYZE=50
    echo     Result: 4 min total cycle fits 10 min interval!
    echo.
    echo  #2 BEST OVERALL - Qwen2.5-72B Q4_K_M (42GB) - SMARTEST:
    echo     ID: lmstudio-community/Qwen2.5-72B-Instruct-GGUF
    echo     File: Qwen2.5-72B-Instruct-Q4_K_M.gguf (42GB)
    echo     RAM: ~44GB (close Chrome/Discord)
    echo     Why: Best open model under 100B, beats Llama 70B
    echo.
    echo  #3 BEST STABLE 70B - Llama-3.1-70B Q4_K_M (40GB):
    echo     ID: lmstudio-community/Meta-Llama-3.1-70B-Instruct-GGUF
    echo     File: Meta-Llama-3.1-70B-Instruct-Q4_K_M.gguf (40GB)
    echo     RAM: ~40GB (leaves 8GB free, very stable)
    echo     Why: Gold standard, most tested, very calibrated
    echo.
    echo  #4 BEST REASONING BUT SLOW - DeepSeek-R1-Distill-Llama-70B Q4_K_M (40GB):
    echo     ID: lmstudio-community/DeepSeek-R1-Distill-Llama-70B-GGUF
    echo     File: Q4_K_M.gguf (40GB)
    echo     Why: Thinks step-by-step before answering, most accurate but SLOW
    echo     WARNING: 7-8 min per market on CPU! Use 5 deep and hourly interval
    echo     Example: "Base rate 60%... Recent news... Market 50% seems low..."
    echo.
    echo  MY PICK FOR YOU WITH 48GB + YOUR MODELS:
    echo    For trading NOW: qwen/qwen3-32b (you have it!) FAST 3 sec
    echo    For max intelligence: Qwen2.5-72B Q4_K_M (42GB) 12 sec
    echo    For best reasoning (slow): DeepSeek-R1-70B Q4 but hourly
    echo.
    echo  STEPS:
    echo    1. Open LM Studio -^> Developer -^> Start Server (port 1234)
    echo    2. Load qwen/qwen3-32b (fast) not R1 (slow) for trading
    echo    3. Test: http://localhost:1234/v1/models in browser
    echo.
    echo ============================================================
    echo.
)

echo [10/10] Final checks...
python -c "import rich, typer, requests, pydantic; print('Core packages OK')" 2>nul
if %errorlevel% equ 0 (
    echo Core packages OK
)

echo.
echo ============================================================
echo  SETUP COMPLETE - 48GB RAM ULTIMATE + R1/X FIX
echo ============================================================
echo.
echo  YOUR MODELS (from log):
echo    deepseek-r1-distill-qwen-32b - SLOW 8 min per market (reasoning)
echo    qwen/qwen3-32b - FAST 3 sec per market - BEST FOR TRADING!
echo    qwen/qwen3.8-27b - FAST similar
echo.
echo  FAST CONFIG FOR 10-MIN CYCLE (RECOMMENDED):
echo    In LM Studio: load qwen/qwen3-32b (unload R1)
echo    .env: SENTIMENT_USE_X=false, MAX_DEEP_ANALYZE=50, SCAN_INTERVAL=10
echo    Result: 500 scan + 0 sentiment + 50*3 sec = 4 min fits 10 min!
echo.
echo  SLOW CONFIG IF YOU KEEP R1:
echo    .env: SENTIMENT_USE_X=false, MAX_DEEP_ANALYZE=5, SCAN_INTERVAL=60
echo    Result: 5*8 min = 40 min per cycle, run hourly
echo.
echo  CONFIG APPLIED FOR 48GB:
echo    - Scan 500 markets, deep 50 (for fast qwen3-32b)
echo    - Auto-detect R1 -^> 5 deep, max_tokens 500, no think tag
echo    - SENTIMENT_USE_X=false (avoids X 404 blocking delay)
echo    - Kelly 6% max, Half-Kelly, min edge 8%, max 6 positions
echo.
echo  NEXT:
echo    1. In LM Studio: unload R1, load qwen/qwen3-32b
echo    2. Check .env has SENTIMENT_USE_X=false and MAX_DEEP_ANALYZE=50
echo    3. Run start.bat
echo.
echo  COMMANDS:
echo    start.bat - Start trading 50 dollars autonomous
echo    start_dashboard.bat - Dashboard http://localhost:8000
echo    python main.py check-llm --provider lm_studio
echo.
echo  GPU TIP: If you have NVIDIA 8GB+ VRAM, enable GPU offload in LM Studio
echo  Settings -^> GPU offload 100%% - makes 70B 5x faster (20 sec -^> 4 sec)
echo.
echo ============================================================
pause
