"""
Betfair Exchange - real adapter over betfairlightweight.

This is the feed that makes the wide market catalogue tradeable. The public
scoreboard feeds (ESPN and friends) carry match odds, spreads and totals and
almost nothing else. Betfair is where corners, cards, bookings, correct score,
half-time and Asian handicap markets actually have a two-sided price - and an
exchange price is a back AND a lay, which is what enables hedging and the
book-vs-exchange arbitrage the arb module models.

Hard rule, same as the rest of the betting subsystem: no credentials means no
markets. The old adapter returned five hardcoded football fixtures with prices
generated by `0.45 + i*0.05`. Those reached the scanner labelled as real
sports markets. This one returns an empty list and a diagnostic instead.

Betfair market types
--------------------
Betfair names its markets by a marketType code. The mapping below is the
bridge from those codes to this project's catalogue keys. Unknown codes are
reported rather than guessed, because misclassifying a market means settling
it against the wrong facts.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Sequence, Tuple

from loguru import logger

from ..markets.base import DataMode, Market, MarketSource, Token


# ---------------------------------------------------------------------------
# Betfair marketType -> this project's catalogue key
# ---------------------------------------------------------------------------

BETFAIR_MARKET_MAP: Dict[str, str] = {
    "MATCH_ODDS": "h2h",
    "MATCH_BET": "h2h",                       # two-way version of MATCH_ODDS
    "MONEY_LINE": "h2h",
    "RUN_LINE": "spreads",
    "POINT_SPREAD": "spreads",
    "DOUBLE_CHANCE": "double_chance",
    "DRAW_NO_BET": "draw_no_bet",
    "ASIAN_HANDICAP": "asian_handicap",
    "HALF_HANDICAP": "asian_handicap",
    "OVER_UNDER_05": "totals",
    "OVER_UNDER_15": "totals",
    "OVER_UNDER_25": "totals",
    "OVER_UNDER_35": "totals",
    "OVER_UNDER_45": "totals",
    "OVER_UNDER_55": "totals",
    "OVER_UNDER_65": "totals",
    "OVER_UNDER_05_H1": "half_time_goals",
    "OVER_UNDER_15_H1": "half_time_goals",
    "BOTH_TEAMS_TO_SCORE": "btts",
    "CORRECT_SCORE": "correct_score",
    "CORRECT_SCORE2": "correct_score",
    "HALF_TIME_SCORE": "half_time_result",
    "HALF_TIME": "half_time_result",
    "HALF_TIME_FULL_TIME": "ht_ft",
    "HT_FT": "ht_ft",
    "CORNER_ODDS": "corners_1x2",
    "CORNERS_1X2": "corners_1x2",
    "OVER_UNDER_CORNERS": "corners_total",
    "CORNER_HANDICAP": "corners_handicap",
    "CARD_ODDS": "cards_1x2",
    "CARDS_1X2": "cards_1x2",
    "OVER_UNDER_CARDS": "cards_total",
    "BOOKING_ODDS": "booking_points",
    "OVER_UNDER_BOOKINGS": "booking_points",
    "RED_CARD": "red_card",
    "ANYTIME_RED_CARD": "red_card",
    "SHOTS_ON_TARGET": "shots_on_target_total",
    "OVER_UNDER_SHOTS": "shots_total",
    "TEAM_TOTAL_GOALS": "team_goals",
    "TO_SCORE_FIRST": "race_to_goals",
    "WIN_TO_NIL": "win_to_nil",
    "CLEAN_SHEET": "clean_sheet",
    "FIRST_GOAL_SCORER": "first_scorer",
    "ANYTIME_SCORER": "anytime_scorer",
    "PLAYER_GOALS": "player_goals",
    "PLAYER_SHOTS": "player_shots",
    "PLAYER_ASSISTS": "player_assists",
    "PLAYER_TO_BE_BOOKED": "player_cards",
    "PLAYER_TACKLES": "player_tackles",
}

# Betfair event type ids for the sports this project covers
BETFAIR_EVENT_TYPES: Dict[str, str] = {
    "soccer": "1",
    "basketball": "7522",
    "football": "6423",
    "baseball": "7511",
    "hockey": "7524",
    "tennis": "2",
}

# Which market types to request, grouped so one call covers the wide card
CORE_MARKET_TYPES: Tuple[str, ...] = (
    "MATCH_ODDS", "MATCH_BET", "DOUBLE_CHANCE", "DRAW_NO_BET",
    "OVER_UNDER_05", "OVER_UNDER_15", "OVER_UNDER_25", "OVER_UNDER_35",
    "BOTH_TEAMS_TO_SCORE", "CORRECT_SCORE", "HALF_TIME_SCORE",
    "HALF_TIME_FULL_TIME", "ASIAN_HANDICAP",
)

SECONDARY_MARKET_TYPES: Tuple[str, ...] = (
    "CORNER_ODDS", "CORNERS_1X2", "OVER_UNDER_CORNERS", "CORNER_HANDICAP",
    "CARD_ODDS", "CARDS_1X2", "OVER_UNDER_CARDS", "BOOKING_ODDS",
    "OVER_UNDER_BOOKINGS", "RED_CARD", "ANYTIME_RED_CARD",
    "TEAM_TOTAL_GOALS", "WIN_TO_NIL", "CLEAN_SHEET",
    "SHOTS_ON_TARGET", "OVER_UNDER_SHOTS",
)

PLAYER_MARKET_TYPES: Tuple[str, ...] = (
    "FIRST_GOAL_SCORER", "ANYTIME_SCORER", "PLAYER_GOALS",
    "PLAYER_SHOTS", "PLAYER_ASSISTS", "PLAYER_TO_BE_BOOKED", "PLAYER_TACKLES",
)


@dataclass
class BetfairRunner:
    """One selectable outcome with both sides of the exchange price."""
    selection_id: int
    name: str
    back_price: Optional[float] = None
    back_size: float = 0.0
    lay_price: Optional[float] = None
    lay_size: float = 0.0
    last_price: Optional[float] = None
    total_matched: float = 0.0
    status: str = ""

    @property
    def has_both_sides(self) -> bool:
        return self.back_price is not None and self.lay_price is not None

    @property
    def spread(self) -> Optional[float]:
        if not self.has_both_sides:
            return None
        return round(self.lay_price - self.back_price, 4)


@dataclass
class BetfairMarket:
    """One Betfair market, mapped onto this project's catalogue."""
    market_id: str
    market_type: str
    catalogue_key: str
    market_name: str
    event_id: str
    event_name: str
    commence_time: Optional[datetime]
    in_play: bool
    runners: List[BetfairRunner] = field(default_factory=list)
    total_matched: float = 0.0
    is_real: bool = True

    @property
    def unknown_type(self) -> bool:
        """True when the Betfair marketType has no catalogue key."""
        return not self.catalogue_key

    @property
    def is_bookable(self) -> bool:
        return any(r.has_both_sides for r in self.runners)


class BetfairClient:
    """
    Thin wrapper over betfairlightweight with honest failure.

    Every method returns empty plus a diagnostic on failure. Nothing here
    fabricates a price, because a fabricated exchange price would be priced
    as a real lay opportunity by the arb module.
    """

    def __init__(self, username: str = "", password: str = "", app_key: str = "",
                 cert_files: Optional[Tuple[str, str]] = None,
                 lightweight: bool = True):
        self.username = username
        self.password = password
        self.app_key = app_key
        self.cert_files = cert_files
        self.lightweight = lightweight
        self._client = None
        self._logged_in = False
        self.last_error: str = ""
        self.unknown_market_types: Dict[str, int] = {}

    # -- connection ---------------------------------------------------------

    @property
    def configured(self) -> bool:
        return bool(self.username and self.password and self.app_key)

    def _ensure_client(self) -> bool:
        if not self.configured:
            self.last_error = ("Betfair credentials not configured (username, password, "
                               "app_key). Refusing to invent exchange prices.")
            return False
        try:
            import betfairlightweight as bflw
        except ImportError:
            self.last_error = "betfairlightweight not installed (pip install betfairlightweight)"
            logger.warning(f"[betfair] {self.last_error}")
            return False

        if self._client is not None:
            return True
        try:
            if self.cert_files:
                self._client = bflw.APIClient(
                    self.username, self.password, self.app_key,
                    certs=self.cert_files)
            else:
                self._client = bflw.APIClient(self.username, self.password, self.app_key)
            return True
        except Exception as e:
            self.last_error = f"client init failed: {type(e).__name__}: {e}"
            logger.warning(f"[betfair] {self.last_error}")
            return False

    def login(self) -> bool:
        if self._logged_in:
            return True
        if not self._ensure_client():
            return False
        try:
            if self.cert_files:
                self._client.login()
            else:
                self._client.login_interactive()
            self._logged_in = True
            logger.info("[betfair] logged in")
            return True
        except Exception as e:
            self.last_error = f"login failed: {type(e).__name__}: {e}"
            logger.warning(f"[betfair] {self.last_error}")
            return False

    # -- discovery ----------------------------------------------------------

    def market_catalogue(self, event_type_id: str,
                         market_types: Sequence[str] = CORE_MARKET_TYPES,
                         max_results: int = 100,
                         in_play_only: bool = False,
                         hours_ahead: int = 48) -> List[BetfairMarket]:
        """
        Fetch real market catalogue for one sport.

        Returns [] with a diagnostic if not logged in - never a placeholder.
        """
        if not self.login():
            return []
        try:
            import betfairlightweight as bflw
            now = datetime.now(timezone.utc)
            market_filter = bflw.filters.market_filter(
                event_type_ids=[event_type_id],
                market_type_codes=list(market_types),
                market_countries=None,
                in_play_only=in_play_only,
                market_start_time_range=bflw.filters.time_range(
                    from_=now.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    to=(now + timedelta(hours=hours_ahead)).strftime("%Y-%m-%dT%H:%M:%SZ"),
                ),
            )
            catalogues = self._client.betting.list_market_catalogue(
                filter=market_filter,
                market_projection=["RUNNER_DESCRIPTION", "MARKET_START_TIME",
                                    "COMPETITION", "EVENT"],
                sort="FIRST_TO_START",
                max_results=max_results,
                lightweight=self.lightweight,
            )
            out: List[BetfairMarket] = []
            for c in catalogues or []:
                out.append(self._parse_catalogue(c))
            logger.info(f"[betfair] {len(out)} markets for event type {event_type_id}")
            return out
        except Exception as e:
            self.last_error = f"catalogue failed: {type(e).__name__}: {e}"
            logger.warning(f"[betfair] {self.last_error}")
            return []

    def market_books(self, market_ids: Sequence[str]) -> Dict[str, Any]:
        """Full back/lay ladder for a batch of markets."""
        if not market_ids:
            return {}
        if not self.login():
            return {}
        try:
            import betfairlightweight as bflw
            books = self._client.betting.list_market_book(
                market_ids=list(market_ids),
                price_projection=bflw.filters.price_projection(
                    price_data=["EX_BEST_OFFERS_DEPTH", "EX_TRADED"]),
                lightweight=self.lightweight,
            )
            return {b["id"] if isinstance(b, dict) else b.market_id: b for b in (books or [])}
        except Exception as e:
            self.last_error = f"market book failed: {type(e).__name__}: {e}"
            logger.warning(f"[betfair] {self.last_error}")
            return {}

    # -- parsing ------------------------------------------------------------

    def _parse_catalogue(self, c: Any) -> BetfairMarket:
        g = (lambda k, d=None: c.get(k, d)) if isinstance(c, dict) else (lambda k, d=None: getattr(c, k, d))
        mtype = g("marketType") or g("market_type") or ""
        catalogue_key = BETFAIR_MARKET_MAP.get(mtype, "")
        if not catalogue_key:
            self.unknown_market_types[mtype] = self.unknown_market_types.get(mtype, 0) + 1

        event = g("event") or {}
        eg = (lambda k, d=None: event.get(k, d)) if isinstance(event, dict) else (
            lambda k, d=None: getattr(event, k, d))

        start = g("marketStartTime") or g("market_start_time")
        commence = None
        if isinstance(start, datetime):
            commence = start
        elif isinstance(start, str):
            try:
                commence = datetime.fromisoformat(start.replace("Z", "+00:00"))
            except ValueError:
                commence = None

        return BetfairMarket(
            market_id=str(g("marketId") or g("market_id") or ""),
            market_type=mtype,
            catalogue_key=catalogue_key,
            market_name=str(g("marketName") or g("market_name") or ""),
            event_id=str(eg("id", "") or ""),
            event_name=str(eg("name", "") or ""),
            commence_time=commence,
            in_play=bool(g("inPlay", False) or g("in_play", False)),
        )

    @staticmethod
    def parse_runners(book: Any) -> Tuple[List[BetfairRunner], float]:
        """Extract back/lay prices from a market book (dict or resource)."""
        runners_raw = (book.get("runners") if isinstance(book, dict)
                       else getattr(book, "runners", None)) or []
        total_matched = float(book.get("totalMatched", 0.0) if isinstance(book, dict)
                             else getattr(book, "total_matched", 0.0) or 0.0)
        out: List[BetfairRunner] = []
        for r in runners_raw:
            rg = (lambda k, d=None: r.get(k, d)) if isinstance(r, dict) else (
                lambda k, d=None: getattr(r, k, d))

            back = rg("ex") or {}
            back_levels = lay_levels = []
            if isinstance(back, dict):
                back_levels = (back.get("availableToBack") or [])
                lay_levels = (back.get("availableToLay") or [])
            else:
                back_levels = getattr(back, "available_to_back", []) or []
                lay_levels = getattr(back, "available_to_lay", []) or []

            def _top(levels, key_price, key_size):
                if not levels:
                    return None, 0.0
                top = levels[0]
                tg = (lambda k, d=None: top.get(k, d)) if isinstance(top, dict) else (
                    lambda k, d=None: getattr(top, k, d))
                price = tg(key_price)
                size = tg(key_size, 0.0) or 0.0
                return (float(price) if price else None), float(size)

            bp, bs = _top(back_levels, "price", "size")
            lp, ls = _top(lay_levels, "price", "size")

            out.append(BetfairRunner(
                selection_id=int(rg("selectionId") or rg("selection_id") or 0),
                name=str(rg("name") or ""),
                back_price=bp, back_size=bs, lay_price=lp, lay_size=ls,
                last_price=(float(rg("lastPriceTraded")) if rg("lastPriceTraded") else None),
                total_matched=float(rg("totalMatched", 0.0) or 0.0),
                status=str(rg("status") or ""),
            ))
        return out, total_matched

    # -- Market bridging ----------------------------------------------------

    def to_market(self, mf: BetfairMarket, data_mode: DataMode = DataMode.LIVE) -> Optional[Market]:
        """
        Convert a Betfair market into the project's Market type.

        Carries BOTH the back and the lay price, because on an exchange the
        lay side is a real tradable price and not just the inverse of the
        back. Downstream code that only reads one side is throwing away the
        exchange's main advantage.
        """
        bookable = [r for r in mf.runners if r.has_both_sides]
        if not bookable:
            return None
        if mf.unknown_type:
            # Refuse rather than settle an unknown market against wrong facts.
            return None

        labels = [r.name for r in bookable]
        back_prices = [r.back_price for r in bookable]
        lay_prices = [r.lay_price for r in bookable]

        return Market(
            id=f"betfair-{mf.market_id}",
            source=MarketSource.POLYMARKET,     # normalised carrier; venue_id is authoritative
            question=f"{mf.event_name} - {mf.market_name}",
            description=(f"Betfair exchange {mf.market_type} ({mf.catalogue_key}); "
                         f"{len(bookable)} selections; two-sided pricing"),
            outcomes=labels,
            outcome_prices=[round(1.0 / p, 4) if p else 0.0 for p in back_prices],
            tokens=[Token(token_id=f"{mf.market_id}:{r.selection_id}", outcome=r.name,
                          price=round(r.back_price, 4))
                    for r in bookable if r.back_price],
            volume=mf.total_matched, volume_24h=0.0,
            liquidity=sum(r.back_size + r.lay_size for r in bookable),
            end_date=mf.commence_time,
            active=not mf.in_play, closed=False,
            slug=mf.market_id, event_slug=mf.event_id,
            market_type="binary" if len(labels) == 2 else "categorical",
            raw={
                "venue": "betfair", "market_type": mf.market_type,
                "catalogue_key": mf.catalogue_key, "market_id": mf.market_id,
                "in_play": mf.in_play, "event_name": mf.event_name,
                "back_prices": back_prices, "lay_prices": lay_prices,
                "back_sizes": [r.back_size for r in bookable],
                "lay_sizes": [r.lay_size for r in bookable],
                "spreads": [r.spread for r in bookable],
                "is_exchange": True, "lay_available": True,
                "data_mode": data_mode.value,
                "data_source": "betfair_exchange_live" if data_mode.can_deploy_live_capital
                               else data_mode.value,
            },
            venue_id="betfair", venue_type="other",
            data_mode=data_mode, is_mock=False,
            data_source="betfair_exchange_live" if data_mode.can_deploy_live_capital
                        else data_mode.value,
        )

    # -- reporting ----------------------------------------------------------

    def health(self) -> Dict[str, Any]:
        return {
            "configured": self.configured,
            "logged_in": self._logged_in,
            "last_error": self.last_error,
            "unknown_market_types": dict(sorted(self.unknown_market_types.items(),
                                                key=lambda kv: -kv[1])[:10]),
            "market_types_mapped": len(BETFAIR_MARKET_MAP),
        }


# ---------------------------------------------------------------------------
# Fetch the full card for one fixture
# ---------------------------------------------------------------------------

def fetch_full_card(client: BetfairClient, event_type_id: str,
                    include_player_markets: bool = False,
                    max_results: int = 200,
                    hours_ahead: int = 48) -> Dict[str, List[BetfairMarket]]:
    """
    Fetch every market type this project can price for one sport.

    Grouped into catalogue keys so the caller gets {catalogue_key: [markets]}.
    Unknown Betfair market types are reported via client.health() rather than
    silently dropped, so new market types become visible instead of vanishing.
    """
    types = list(CORE_MARKET_TYPES) + list(SECONDARY_MARKET_TYPES)
    if include_player_markets:
        types += list(PLAYER_MARKET_TYPES)

    markets = client.market_catalogue(event_type_id, market_types=types,
                                      max_results=max_results, hours_ahead=hours_ahead)
    if not markets:
        return {}

    books = client.market_books([m.market_id for m in markets[:max_results]])
    grouped: Dict[str, List[BetfairMarket]] = {}
    for m in markets:
        book = books.get(m.market_id)
        if book is not None:
            m.runners, m.total_matched = BetfairClient.parse_runners(book)
        if m.is_bookable and not m.unknown_type:
            grouped.setdefault(m.catalogue_key, []).append(m)

    logger.info(f"[betfair] full card: {sum(len(v) for v in grouped.values())} bookable "
                f"markets across {len(grouped)} catalogue keys")
    return grouped
